# Power Iteration and its Variants

In [33]:
import numpy as np
import numpy.linalg as la
np.set_printoptions(precision=3)

Let's  prepare a matrix with some random or deliberately chosen eigenvalues:

In [36]:
n = 6

if 1:
    np.random.seed(70)
    eigvecs = np.random.randn(n, n)
    eigvals = np.sort(np.random.randn(n))
    # Uncomment for near-duplicate largest-magnitude eigenvalue
    # eigvals[1] = eigvals[0] + 1e-3

    A = eigvecs.dot(np.diag(eigvals)).dot(la.inv(eigvecs))
    print(eigvals)
    
else:
    # Complex eigenvalues
    np.random.seed(40)
    A = np.random.randn(n, n)
    print(la.eig(A)[0])

[-2.668 -0.958 -0.33  -0.292 -0.186 -0.144]


Let's also pick an initial vector:

In [37]:
x0 = np.random.randn(n)
x0

array([ 2.269,  0.664,  0.899, -0.366,  0.463,  0.08 ])

### Power iteration

In [42]:
x = x0

Now implement plain power iteration.

In [52]:
for i in range(20):
    xold = x.copy()
    x = A @ x
    #print(x / xold)
    print('|eig| ~', x[0] / xold[0])

|eig| ~ -0.14418092415134545
|eig| ~ -0.14418092372472432
|eig| ~ -0.14418092317209322
|eig| ~ -0.1441809224353315
|eig| ~ -0.144180921067802
|eig| ~ -0.14418091162171445
|eig| ~ -0.14418075737246108
|eig| ~ -0.14417793014921995
|eig| ~ -0.144125655200453
|eig| ~ -0.14315812209947684
|eig| ~ -0.1251220367722499
|eig| ~ 0.2621610739580601
|eig| ~ -4.2789594330255145
|eig| ~ -2.721944036124406
|eig| ~ -2.670526709391543
|eig| ~ -2.6678061903287826
|eig| ~ -2.667659360033327
|eig| ~ -2.6676514394147017
|eig| ~ -2.667651016623914
|eig| ~ -2.6676509956763574


* What's the problem with this method?
* Does anything useful come of this?
* How do we fix it?

### Normalized power iteration

Back to the beginning: Reset to the initial vector.

In [53]:
x = x0/la.norm(x0)

Implement normalized power iteration.

In [54]:
for i in range(10):
    x = A @ x
    nrm = la.norm(x)
    x = x/nrm
    print('|eig| ~', nrm)

print(x)

|eig| ~ 10.411000127344384
|eig| ~ 2.931342228363236
|eig| ~ 2.7009617827093924
|eig| ~ 2.674705231024035
|eig| ~ 2.6697249538939403
|eig| ~ 2.66834923020146
|eig| ~ 2.6678967063646497
|eig| ~ 2.667738661394379
|eig| ~ 2.6676824100811145
|eig| ~ 2.667662268743778
[ 0.237 -0.845 -0.138  0.181 -0.151 -0.394]


In [55]:
A @ x - - nrm * x

array([ 1.488e-06, -6.763e-06,  1.802e-06, -5.107e-06, -5.169e-06,
       -3.943e-06])

* What do you observe about the norm?
* What about the sign?
* What is the vector $x$ now?

Extensions:

* Now try the matrix variants above.
* Suggest a better way of estimating the eigenvalue. [Hint](https://en.wikipedia.org/wiki/Rayleigh_quotient)

------
### Inverse iteration

What if we want the smallest eigenvalue (by magnitude)?

Once again, reset to the beginning.

In [56]:
x = x0/la.norm(x0)

In [57]:
for i in range(30):
    x = la.solve(A, x)
    nrm = la.norm(x)
    x = x/nrm
    print('|eig| ~', 1/nrm)
print(nrm)

|eig| ~ 0.050405197175442534
|eig| ~ 0.14831364453292906
|eig| ~ 0.14305586701296166
|eig| ~ 0.1394127194194322
|eig| ~ 0.13829144493812798
|eig| ~ 0.13837008218756022
|eig| ~ 0.13899785982251972
|eig| ~ 0.13980464470770787
|eig| ~ 0.14060157080716562
|eig| ~ 0.14130894974197075
|eig| ~ 0.1419038220900869
|eig| ~ 0.1423891881500867
|eig| ~ 0.1427781420086042
|eig| ~ 0.14308635900968578
|eig| ~ 0.14332883588966172
|eig| ~ 0.14351867777732702
|eig| ~ 0.14366682252440854
|eig| ~ 0.14378216386212161
|eig| ~ 0.143871819260615
|eig| ~ 0.1439414269808849
|eig| ~ 0.14399542340286198
|eig| ~ 0.14403728313211261
|eig| ~ 0.1440697187196691
|eig| ~ 0.14409484291673352
|eig| ~ 0.1441142985528363
|eig| ~ 0.1441293614887531
|eig| ~ 0.14414102168580564
|eig| ~ 0.1441500467473268
|eig| ~ 0.144157031557096
|eig| ~ 0.14416243696355052
6.936619698325689


* What's the computational cost per iteration?
* Can we make this method search for a specific eigenvalue?

------
### Inverse Shift iteration

What if we want the eigenvalue closest to a give value $\sigma$?

Once again, reset to the beginning.

In [64]:
x = x0/la.norm(x0)

In [69]:
sigma = -1
A_sigma = A-sigma*np.eye(A.shape[0])
for i in range(30):
    x = la.solve(A_sigma, x)
    nrm = la.norm(x)
    x = x/nrm
    print('|eig| ~', 1/nrm)
print(nrm)
print(eigvals - sigma)

|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
|eig| ~ 0.04202907081564314
|eig| ~ 0.042029070815643145
|eig| ~ 0.042029070815643124
23.793055154286264
[-1.668  0.042  0.67   0.708  0.814  0.856]


--------------
### Rayleigh quotient iteration

Can we feed an estimate of the current approximate eigenvalue back into the calculation? (Hint: Rayleigh quotient)

Reset once more.

In [75]:
x = x0/la.norm(x0)

Run this cell in-place (Ctrl-Enter) many times.

In [77]:
for i in range(10):
    sigma = np.dot(x, np.dot(A, x))/np.dot(x, x)
    x = la.solve(A-sigma*np.eye(n), x)
    x = x/la.norm(x)
    print('|eig| ~', sigma)
print(eigvals)

|eig| ~ -0.14418092560963328
|eig| ~ -0.14418092560962567
|eig| ~ -0.14418092560963539
|eig| ~ -0.14418092560962883
|eig| ~ -0.14418092560963178
|eig| ~ -0.14418092560962933
|eig| ~ -0.14418092560963108
|eig| ~ -0.1441809256096294
|eig| ~ -0.1441809256096311
|eig| ~ -0.14418092560962886
[-2.668 -0.958 -0.33  -0.292 -0.186 -0.144]


* What's a reasonable stopping criterion?
* Computational downside of this iteration?