In [2]:
import numpy as np

Start with matrix $A$.  What happens to $A_k$ in each iteration?
1. If $A$ is standard full matrix, then each $A_k$ remains full
2. If $A$ is upper triangular, then $A_k$ will stay upper triangular
3. If $A$ is upper Hessenberg, then $A_k$ will stay upper Hessenberg

How do we transform $A$ into an upper Hessenberg matrix?

In [8]:
A = np.random.rand(5,5)
case = 3
if case == 2:
    A = np.triu(A, k=0)
if case == 3:
    A = np.triu(A, k=-1)

In [9]:
Q, R = np.linalg.qr(A)
A1 = R @ Q
Q, R = np.linalg.qr(A1)
A2 = R @ Q

with np.printoptions(precision=2):
    print(A)
    print(A1)
    print(A2)

[[0.32 0.97 0.5  0.48 0.63]
 [0.02 0.1  0.3  0.7  0.42]
 [0.   0.35 0.68 0.98 0.78]
 [0.   0.   0.38 0.33 0.54]
 [0.   0.   0.   0.31 0.4 ]]
[[ 0.39  0.59 -0.9  -0.83 -0.14]
 [ 0.03  0.73 -1.04 -0.36 -0.76]
 [ 0.   -0.43  0.49  0.18  0.67]
 [ 0.    0.    0.41  0.01  0.36]
 [ 0.    0.    0.    0.2   0.22]]
[[ 0.43  1.04  0.7   0.17  0.7 ]
 [ 0.05  1.26  0.22  0.98  0.58]
 [ 0.    0.23 -0.08  0.29  0.36]
 [ 0.    0.    0.19  0.21  0.06]
 [ 0.    0.    0.    0.26  0.01]]


In [11]:
with np.printoptions(precision=2):
    print(Q)

[[-9.98e-01  5.72e-02  9.40e-03  9.31e-04 -3.51e-02]
 [-6.77e-02 -8.42e-01 -1.38e-01 -1.37e-02  5.16e-01]
 [-0.00e+00  5.36e-01 -2.19e-01 -2.16e-02  8.15e-01]
 [-0.00e+00 -0.00e+00  9.66e-01 -6.87e-03  2.59e-01]
 [-0.00e+00 -0.00e+00  0.00e+00  1.00e+00  2.65e-02]]


In [ ]:
R