# 3x3 Householder QR Demo

This demo constructs a $3\times 3$ QR factorization using Householder reflectors.

In [11]:
import numpy as np
import numpy.linalg as la

In [12]:
n = 3

e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

A = np.random.randn(n, n)
A

array([[-0.05841765, -0.03351919, -0.56681095],
       [ 1.47098898, -1.64923321,  0.96483702],
       [ 0.21379242, -0.53373423, -1.21355024]])

Householder reflector:
$$I-2\frac{vv^T}{v^Tv}$$

Choose $v=a-\|a\|e_1$.

In [13]:
a = A[:, 0]
v = a-la.norm(a)*e1

H1 = np.eye(3) - 2*np.outer(v, v)/(v@v)

In [14]:
A1 = H1 @ A
A1

array([[ 1.48759147e+00, -1.70621716e+00,  8.01919453e-01],
       [ 1.77601596e-16, -5.77029662e-02, -3.37475690e-01],
       [ 2.81121599e-17, -3.02422438e-01, -1.40282738e+00]])

NB: Never build full Householder matrices in actual code! (Why? How?)

In [17]:
a = A1[:, 1].copy()
a[0] = 0
v = a-la.norm(a)*e2

H2 = np.eye(3) - 2*np.outer(v, v)/(v@v)

In [18]:
R = H2 @ A1
R

array([[ 1.48759147e+00, -1.70621716e+00,  8.01919453e-01],
       [-6.09003466e-17,  3.07878163e-01,  1.44121889e+00],
       [-1.69185603e-16,  2.07475103e-17,  6.85755676e-02]])

In [9]:
Q = np.dot(H2, H1).T
la.norm(np.dot(Q, R) - A)

4.3177542613803813e-16

In [10]:
Q.T @ Q

array([[ 1.00000000e+00, -8.26853021e-17,  5.83068246e-17],
       [-8.26853021e-17,  1.00000000e+00,  1.59500395e-16],
       [ 5.83068246e-17,  1.59500395e-16,  1.00000000e+00]])