# Normal Equations vs Pseudoinverse

In [1]:
import numpy as np
import numpy.linalg as la

Here's a simple overdetermined linear system, which we'll solve using both the normal equations and the pseudoinverse:

In [2]:
A = np.random.randn(5, 3)
b = np.random.randn(5)

### Normal Equations

Solve $Ax\cong b$ using the normal equations:

In [3]:
x1 = la.solve(A.T@A, A.T@b)
x1

array([ 0.82294545, -0.29646992,  0.64470835])

### Pseudoinverse

Solve $Ax\cong b$ using the pseudoinverse:

In [4]:
U, sigma, VT = la.svd(A)
print(U)
print(sigma)
print(VT)

[[-0.89908983  0.39719809 -0.18263061 -0.02034633  0.01016074]
 [ 0.31685562  0.86474015  0.29646864  0.10333053 -0.23077291]
 [ 0.26103651  0.2609165  -0.63341647 -0.63752742  0.23690689]
 [ 0.15189883  0.09432106 -0.62119014  0.75607273  0.10250426]
 [ 0.00516529  0.13222809  0.30275202  0.10402714  0.93808775]]
[2.66518665 1.81712361 1.56596661]
[[ 0.26389466 -0.22363577  0.9382679 ]
 [ 0.2407838   0.95722753  0.1604326 ]
 [ 0.93401433 -0.1835824  -0.30645511]]


In [5]:
Sigma_inv = np.zeros_like(A.T)
Sigma_inv[:3,:3] = np.diag(1/sigma)
Sigma_inv

array([[0.37520824, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.5503203 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.63858322, 0.        , 0.        ]])

In [6]:
pinv = VT.T @ Sigma_inv @ U.T
x2 = pinv @ b
x2

array([ 0.82294545, -0.29646992,  0.64470835])

In [7]:
la.norm(x1-x2)

5.20740757162067e-16