In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sla
%matplotlib inline

In [2]:
A = np.random.rand(5, 5)
x = np.array([1.,2,3,4,5])
b = A @ x

In [3]:
P, L, U = sla.lu(A)

In [5]:
A - P @ L @ U

array([[-3.46944695e-18,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  5.55111512e-17,  1.21430643e-17,
         0.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00, -1.11022302e-16,
        -1.11022302e-16,  0.00000000e+00]])

In [7]:
P.T @ P

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
y = sla.solve_triangular(L, P.T @ b, lower=True, unit_diagonal=True)
x = sla.solve_triangular(U, y)
x

array([1., 2., 3., 4., 5.])

In [ ]:
P

In [ ]:
P @ b

In [4]:
y = sla.lu?

Signature: sla.lu(a, permute_l=False, overwrite_a=False, check_finite=True)
Docstring:
Compute pivoted LU decomposition of a matrix.

The decomposition is::

    A = P L U

where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.

Parameters
----------
a : (M, N) array_like
    Array to decompose
permute_l : bool, optional
    Perform the multiplication P*L (Default: do not permute)
overwrite_a : bool, optional
    Whether to overwrite data in a (may improve performance)
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.

Returns
-------
**(If permute_l == False)**

p : (M, M) ndarray
    Permutation matrix
l : (M, K) ndarray
    Lower triangular or trapezoidal matrix with unit diagonal.
    K = min(M, N)
u : (K, N) ndarray
    Upper triangular

In [ ]:
y = sla.lu