In [8]:
import pyamg
import numpy as np

In [2]:
!pip install pyamg

Processing /Users/lukeo/Library/Caches/pip/wheels/1a/0a/10/3002018fd50f1011e66e719f89cdb89399bf2eaa965aac821a/pyamg-4.0.0-cp38-cp38-macosx_10_15_x86_64.whl
  Using cached pytest-6.0.2-py3-none-any.whl (270 kB)
  Using cached pybind11-2.5.0-py2.py3-none-any.whl (296 kB)
  Using cached iniconfig-1.0.1-py3-none-any.whl (4.2 kB)
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
  Using cached more_itertools-8.5.0-py3-none-any.whl (44 kB)
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
You should consider upgrading via the '/Users/lukeo/.virtualenvs/cs450-f20/bin/python -m pip install --upgrade pip' command.


In [4]:
A = pyamg.gallery.poisson((5,5), format='csr')

/Users/lukeo/.virtualenvs/cs450-f20/lib/python3.8/site-packages/pyamg/gallery/stencil.py:114: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  diag[s] = 0
/Users/lukeo/.virtualenvs/cs450-f20/lib/python3.8/site-packages/pyamg/gallery/stencil.py:110: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  diag[s] = 0


In [5]:
A

<25x25 sparse matrix of type '<class 'numpy.float64'>'
	with 105 stored elements in Compressed Sparse Row format>

In [21]:
I = np.where(np.diff(A.indptr)==4)[0]

In [22]:
I

array([ 1,  2,  3,  5,  9, 10, 14, 15, 19, 21, 22, 23])

In [32]:
B = A[I,:][:,I]

In [24]:
B

<12x12 sparse matrix of type '<class 'numpy.float64'>'
	with 28 stored elements in Compressed Sparse Row format>

In [25]:
B.shape

(12, 12)

In [26]:
A.spae

AttributeError: spae not found

In [27]:
A.shape

(25, 25)

In [33]:
B

<12x12 sparse matrix of type '<class 'numpy.float64'>'
	with 28 stored elements in Compressed Sparse Row format>

In [31]:
B.toarray()

array([[ 4., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  4., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  4.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  4.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  4.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  4.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  4., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  4.]])

In [34]:
np.diff(B.indptr)

array([2, 3, 2, 2, 2, 3, 3, 2, 2, 2, 3, 2], dtype=int32)